version: '2.10.2'
services:

  # # # Elasticsearch
  elastic.local:
    image: elasticsearch:8.1.3
    container_name: elasticsearch
    restart: always
    #
    volumes:
     - ./elasticsearch/data:/usr/share/elasticsearch/data/
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

     - ./certs/elasticsearch.crt:/usr/share/elasticsearch/config/certs/elasticsearch.crt
     - ./certs/elasticsearch.key:/usr/share/elasticsearch/config/certs/elasticsearch.key
     - ./certs/ca.crt:/usr/share/elasticsearch/config/certs/ca.crt
    # - ./certs/ca.key:/usr/share/elastic/config/certs/ca.key

    # - ./elasticsearch/config/certs:/usr/share/elasticsearch/config/certs/
    #
    ports:
      - 9200:9200
      - 9300:9300
    #
    healthcheck:
      test: curl --cacert /usr/share/elasticsearch/config/certs/ca.crt https://elastic.local:9200/ | grep -q 'missing authentication credentials'
      interval: 20s
      timeout: 10s
      retries: 5
    #
    mem_limit: 4096m
